### PR TITLE
fixed bugs when searching blog posts with tags enabled

### PR DESCRIPTION
**Pull request by rubichandrap**
installed material icons
added search icons to refer user to search page

### CODE REVIEW

**Review by aldy505 — APPROVED** [review]
looks a bit too big on my phone (iphone x), but I guess that might be a problem for later, as we're still focusing on the features. 

image

**Comment by rubichandrap** [comment]
> looks a bit too big on my phone (iphone x), but I guess that might be a problem for later, as we're still focusing on the features.
> 
> image

Screenshot_20210903-000534

Looks totally fine for me

**Comment by aldy505** [comment]
@elianiva review pak

**Review by elianiva — APPROVED** [review]

**Comment by aldy505** [comment]
@rubichandrap sudah ready to merge kah?

**Pull request merged**
