### PR TITLE
feat: highlighter feature

### PR DESCRIPTION
**Pull request by linefile**
Highlight line

feat: code highlight line

### CODE REVIEW

**Comment by linefile** [comment]
Mending yg mana buat line number?
1. Ga ush tulis di markdown (minimal 5 baris https://github.com/teknologi-umum/blog/pull/80#issuecomment-1008158495)
2. Tulis `no-line-numbers` di code block klo gk mau ada line number.
```markdown
```go no-line-numbers
  type struct {
    ...
  }
``​`
```
Atau gimana?

**Comment by aldy505** [comment]
yang kedua sebenernya oke, tapi harus kasih documentation lagi buat writernya. karena kita udah rada melenceng dari GFM kan.

btw, telegramnya apa om?

cc @elianiva

**Comment by linefile** [comment]
> yang kedua sebenernya oke, tapi harus kasih documentation lagi buat writernya. karena kita udah rada melenceng dari GFM kan.
> 
> btw, telegramnya apa om?
> 
> cc @elianiva

okee

**Comment by linefile** [comment]
> Saya setuju no 2. btw shiki support numbering langsung??

kayanya belum, ini emang ada update dari shikinya https://github.com/shikijs/shiki/pull/259, bisa tambah classname di specific line

**Comment by herlangga72** [comment]
> Mending yg mana buat line number?
> 
> 1. Ga ush tulis di markdown (minimal 5 baris [feat: add numbering on pre tag #80 (comment)](https://github.com/teknologi-umum/blog/pull/80#issuecomment-1008158495))
> 2. Tulis `no-line-numbers` di code block klo gk mau ada line number.
> 
> ```gfm
> ```go no-line-numbers
>   type struct {
>     ...
>   }
> ``​`
> ```
> 
> Atau gimana?

jadi ini belum bisa diterapin kah ?

**Comment by linefile** [comment]
btw om,

mYCo9fAqUs
empty line nya gk bisa diselect

**Comment by linefile** [comment]
> jadi ini belum bisa diterapin kah ?

eh kirain yg highlight line, itu cuma css aja tinggal tambahin classname

**Comment by linefile** [comment]
> btw om,
> 
> mYCo9fAqUs
> 
> empty line nya gk bisa diselect

ok, fixed :)
msedge_98u3J7Gjpb

**Comment by elianiva** [comment]
harus dibikinin documentation buat yg mau kontribusi biar tau kalo ada fitur ini

**Comment by elianiva** [comment]
MDX v2 is removing the ability to do `node.type = "html"` from remark plugin, so we need to parse the html back to an AST, which is tedious. Instead of doing that, I decided to use https://rehype-pretty-code.netlify.app/ in #106 which also has line highlight feature.

Thanks for all of your work, but I think this PR can be closed once that PR is merged.

**Pull request closed without merging**
